name: Python Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        check-latest: true
        cache: 'pip'
      continue-on-error: true
    
    - name: Upgrade pip
      run: |
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip setuptools wheel
      continue-on-error: false
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Verify dependencies
      run: |
        pip freeze > installed.txt
        diff requirements.txt installed.txt || true
        
    - name: Verify Python installation
      run: |
        python --version
        pip --version